# Generated by Django 4.2.1 on 2023-07-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_remove_employee_first_name_remove_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Login Duration'),
        ),
        migrations.AddField(
            model_name='employee',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Login Time'),
        ),
        migrations.AddField(
            model_name='employee',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Logout Time'),
        ),
    ]
