# Generated by Django 3.2.11 on 2023-07-14 06:00

from django.db import migrations
import login.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_employee_duration_employee_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='daily_duration_list',
            field=login.models.ListField(null=True, token=',', verbose_name='Daily Duration List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_login_list',
            field=login.models.ListField(null=True, token=',', verbose_name='Daily Login List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_logout_list',
            field=login.models.ListField(null=True, token=',', verbose_name='Daily Logout List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_duration_list',
            field=login.models.ListField(null=True, token=',', verbose_name='Monthly Duration List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_login_list',
            field=login.models.ListField(null=True, token=',', verbose_name='Monthly Login List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='monthly_logout_list',
            field=login.models.ListField(null=True, token=',', verbose_name='Monthly Logout List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_duration_list',
            field=login.models.ListField(null=True, token=',', verbose_name='Weekly Duration List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_login_list',
            field=login.models.ListField(null=True, token=',', verbose_name='Weekly Login List'),
        ),
        migrations.AddField(
            model_name='employee',
            name='weekly_logout_list',
            field=login.models.ListField(null=True, token=',', verbose_name='Weekly Logout List'),
        ),
    ]
