# Generated by Django 3.2.11 on 2023-07-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_auto_20230714_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_weekly_update',
            field=models.DateField(null=True, verbose_name='Last Weekly Update'),
        ),
    ]
