# Generated by Django 3.2.11 on 2023-07-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_employee_last_weekly_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='duration',
            field=models.CharField(max_length=200, null=True, verbose_name='Login Duration'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='login_time',
            field=models.CharField(max_length=200, null=True, verbose_name='Login Time'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='logout_time',
            field=models.CharField(max_length=200, null=True, verbose_name='Logout Time'),
        ),
    ]
