# Generated by Django 3.2.11 on 2023-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_auto_20230714_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_monthly_update',
            field=models.DateField(null=True, verbose_name='Last Monthly Update'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=50, null=True, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='login_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='No. Of LogIns'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='logout_counter',
            field=models.IntegerField(default=0, null=True, verbose_name='No. Of LogOuts'),
        ),
    ]
