# Generated by Django 3.2.11 on 2023-07-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_auto_20230717_1112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListModel',
        ),
        migrations.AddField(
            model_name='employee',
            name='permission',
            field=models.CharField(max_length=50, null=True, verbose_name='Permission'),
        ),
    ]
