# Generated by Django 3.2.11 on 2023-07-18 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_employee_work_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_time',
        ),
    ]
