# Generated by Django 3.2.11 on 2023-07-18 08:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_remove_employee_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_time',
            field=models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MaxValueValidator(datetime.timedelta(seconds=28800))], verbose_name='Work Time'),
        ),
    ]
