# Generated by Django 3.2.11 on 2023-07-19 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_remove_employee_remaining_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='remaining_time',
            field=models.DurationField(default=datetime.timedelta(seconds=28800), verbose_name='Remaining Time'),
        ),
    ]
