# Generated by Django 3.2.11 on 2023-07-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_changepermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_teamLead',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ChangePermissions',
        ),
    ]
