# Generated by Django 3.2.11 on 2023-07-20 06:06

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0044_auto_20230719_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='remaining_time',
            field=models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))], verbose_name='Remaining Time'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_time',
            field=models.DurationField(default=datetime.timedelta(0), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0)), django.core.validators.MaxValueValidator(datetime.timedelta(seconds=28800))], verbose_name='Work Time'),
        ),
    ]
